SampleApp1/Models/BirthDateUtility.cs
using System;

namespace SampleApp1.Models
{
    public static class BirthDateUtility
    {
        public static int GetAge(DateTime birthDate)
        {
            throw new NotImplementedException();
        }
    }
}

SampleApp1/Models/Customer.cs
using System;
using System.IO;
using System.Linq;

namespace SampleApp1.Models
{
    public sealed class Customer
    {
        public Customer(string name, string furigana, Gender gender, string phoneNumber, DateTime birthDate)
        {
            Name = name;
            Furigana = furigana;
            Gender = gender;
            PhoneNumber = phoneNumber;
            BirthDate = birthDate;
        }

        public string Name { get; }
        public string Furigana { get; }
        public Gender Gender { get; }
        public string PhoneNumber { get; }
        public DateTime BirthDate { get; }

        public static Customer[] LoadAll()
        {
            return File.ReadAllLines(@"Data\customers.csv")
                .Select(Parse)
                .ToArray();
        }

        public static Customer Parse(string line)
        {
            var cells = line.Split(',');
            return new Customer(cells[1], cells[2], ParseGender(cells[3]), cells[4], ParseBirthDate(cells[5]));
        }

        private static Gender ParseGender(string s)
        {
            switch (s)
            {
                case "男": return Gender.Male;
                case "女": return Gender.Female;
                default: return Gender.NotKnown;
            }
        }

        private static DateTime ParseBirthDate(string s)
        {
            if (DateTime.TryParse(s, out var result)) return result;

            return DateTime.MinValue;
        }
    }
}

SampleApp1/Models/ErrorViewModel.cs
namespace SampleApp1.Models
{
    public sealed class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SampleApp1/Models/Gender.cs
namespace SampleApp1.Models
{
    public enum Gender
    {
        NotKnown = 0,
        Male = 1,
        Female = 2,
        NotApplicable = 9
    }
}

SampleApp1/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using SampleApp1.Models;

namespace SampleApp1.Controllers
{
    public sealed class CustomerController : Controller
    {
        // GET
        public IActionResult Index()
        {
            var customers = Customer.LoadAll();

            return View(customers);
        }
    }
}

SampleApp1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SampleApp1.Models;

namespace SampleApp1.Controllers
{
    public sealed class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

SampleApp1/Views/Customer/Index.cshtml
@model SampleApp1.Models.Customer[]

@functions {    }

@{
    ViewBag.Title = "顧客一覧";
    Layout = "_Layout";
}

<h2>顧客一覧</h2>

<table class="table">
    <thead>
    <tr>
        <th>氏名</th>
        <th>フリガナ</th>
        <th>電話番号</th>
        <th>生年月日</th>
        <th>年齢</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var customer in Model)
    {
        <tr>
            <td>@customer.Name</td>
            <td>@customer.Furigana</td>
            <td>@customer.PhoneNumber</td>
            <td>@customer.BirthDate.ToString("yyyy/MM/dd")</td>
            <td>@BirthDateUtility.GetAge(customer.BirthDate)</td>
        </tr>
    }
    </tbody>
</table>

SampleApp1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SampleApp1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br/>
    Redmond, WA 98052-6399<br/>
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br/>
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SampleApp1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive"/>
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive"/>
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive"/>
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a>
            </li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a>
            </li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a>
            </li>
            <li>
                <a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a>
            </li>
        </ul>
    </div>
</div>

SampleApp1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SampleApp1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SampleApp1</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Customer" asp-action="Index">顧客一覧</a>
                </li>
                <li>
                    <a href="~/slide/index.html" target="slide">スライド</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<partial name="_CookieConsentPartial"/>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2019 - SampleApp1</p>
    </footer>
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", false)
</body>
</html>